name: Deploy WordPress to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'wordpress/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Prepare WordPress files
      run: |
        cd wordpress
        # Download WordPress core
        curl -O https://wordpress.org/latest.zip
        unzip latest.zip
        cp -r wordpress/* .
        rm -rf wordpress latest.zip
        
        # Install WP-CLI
        curl -O https://raw.githubusercontent.com/wp-cli/wp-cli/v2.8.1/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        
        # Install WordPress plugins for headless setup
        wp plugin install wp-cors --allow-root --path=.
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./wordpress